### ISSUE TITLE
Administrative security review

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/swigcsm#29]
As part of the USGS Release process the repo needs an administrative code review as per the [USGS Software Management website](https://www.usgs.gov/software-management/types-software-review).

**Comment by jessemapel** [comment]
I've reviewed all the files in the repository and there are no security issues.

**Comment by AustinSanders** [comment]
I conducted a review on 05/09/22-05/10/22 to search for PII, absolute file paths, hostnames/IPs, and usernames/passwords.  This repository does not contain any of these items.
