### ISSUE TITLE
Domain Review

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/swigcsm#30]
This issue is for the Domain Review step of the USGS release process. More information can be found on the [USGS Software Management Website](https://www.usgs.gov/software-management/types-software-review).

**Comment by AustinSanders** [comment]
A domain review has been conducted on this software the week of 03/10/22.

Swigcsm is a set of swig wrappers around USGSCSM, and, as such, there are limited scientific/industry standards, algorithms, or publications to which it can be compared.  One possible comparison is between the camera models implemented in the underlying CSM library and the well-established camera models contained in ISIS.  A table of  comparisons between CSM's output and ISIS's output can be found at [here](https://github.com/USGS-Astrogeology/knoten/tree/master/), and the Jupyter notebooks used to generate those results can be found [here](https://github.com/USGS-Astrogeology/knoten/tree/master/examples).

Based on the results of the comparison, this software passes domain review.
